backend:
  name: github
  repo: phuchoa2001/jamstack-basic
  # optional, defaults to master
  # branch: main

local_backend: true

display_url: https://vigorous-mahavira-319660.netlify.app/
logo_url: https://vigorous-mahavira-319660.netlify.app/img/baked-logo.svg

media_folder: "db/"
public_folder: "img"

collections:
  - name: "Post"
    label: "Post"
    folder: "_db/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}