backend:
  name: github
  repo: phuchoa2001/jamstack-basic
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Tiêu đề",
          name: "title",
          widget: "string",
          hint: "Nhập tiêu đề bài viết",
          required: true,
        }
      - {
          label: "Mô tả",
          name: "desc",
          widget: "text",
          hint: "Nhập mô tả bài viết",
          required: true,
        }
      - {
          label: "Nội dung",
          name: "body",
          widget: "markdown",
          hint: "Viết nội dung chi tiết của bài viết",
          required: true,
        }
      - {
          label: "Tác giả",
          name: "author",
          widget: "string",
          hint: "Nhập tên tác giả",
          default: "Đặng Phúc Hòa",
        }
      - {
          label: "Ngày",
          name: "date",
          widget: "datetime",
          hint: "Chọn ngày và giờ đăng bài viết",
          required: true,
        }
      - {
          label: "Danh mục",
          name: "category",
          widget: "string",
          hint: "Nhập danh mục hoặc chủ đề của bài viết",
          required: true,
        }
      - {
          label: "Hình ảnh",
          name: "image",
          widget: "string",
          hint: "Nhập đường dẫn đến hình ảnh đại diện",
          required: true,
        }
      - {
          label: "Thẻ (Tags)",
          name: "tags",
          widget: "list",
          field: { name: "tag", label: "Tag", widget: "string" },
          hint: "Nhập từ khóa hoặc thẻ phân loại bài viết . lấy slug bằng cách /api/getslug?title=title",
        }
      - {
          label: "URL duy nhất",
          name: "slug",
          widget: "string",
          hint: "Nhập URL duy nhất cho bài viết",
          required: true,
        }
      - {
          label: "Trạng thái",
          name: "status",
          widget: "select",
          options:
            [
              { label: "Đã xuất bản", value: "published" },
              { label: "Nháp", value: "draft" },
              { label: "Ẩn", value: "hidden" },
            ],
          hint: "Chọn trạng thái hiện tại của bài viết",
          default: "draft",
        }
