name: Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        uses: repo-sync/github-sync@v2
        with:
          source_branch: ${{ github.head_ref }}
          destination_branch: ${{ github.base_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
